#!/bin/bash

MY_PATH="`dirname \"$0\"`"              
MY_PATH="`( cd \"$MY_PATH\" && pwd )`" 
echo "$MY_PATH"
java -jar $MY_PATH/pshell-1.19.0-fat.jar -o -z -fda_browser -laf=dark -data=. -hide=tabStatus -dfmt=fda -dlay=fda $@
