#!/bin/bash

/opt/gfa/pshell/pshell \
     -l \
     -r \
     -laf=dark \
     -home=/opt/gfa/pshell/config/pshell_sh \
     -outp=~/pshell/home \
     -scpt=~/pshell/home/script \
     -strh=~/pshell/home/stripchart \
     -pipeline_server=sf-daqsync-01:8889 \
     -camera_server=sf-daqsync-01:8888 \
     -py3 \
     -version=default \
     ${1+"$@"}

